Fix #23: Add example structure to README
yiisoft/file-router pull request #24
Opened 2024-12-08 20:38 UTC by samdark

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌

2024-12-09 20:04 UTC, vjik requested changes

2024-12-09 20:04 UTC, vjik commented on README.md
> +                'withBaseControllerDirectory()' => 'Controller',
```suggestion
                'withBaseControllerDirectory()' => ['Controller'],
```

2024-12-09 20:04 UTC, vjik commented on README.md
> +- `GET /user/profile` → `ViewController::index()`
Seems, here should be route `/user/profile/view` or `ViewController` should be renamed to `IndexController`, isn't he?

2024-12-10 07:51 UTC, vjik approved these changes

2024-12-10 11:57 UTC, xepozz requested changes

2024-12-10 11:57 UTC, xepozz commented on README.md
> +By default, the following structure of the app could be used assuming `MyApp\Package1` points to `src` directory:
```suggestion
By default, the following structure of the app could be used assuming `App` points to `src` directory:
```

2024-12-10 16:18 UTC, xepozz approved these changes

2024-12-10 23:20 UTC, merged